name: todo_assignment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  flutter_screenutil: 5.5.3+2
  flutter_svg: 1.1.0
  glassmorphism: 3.0.0
  flutter_slidable: 1.3.0
  equatable: 2.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/font/
    - assets/images/
  fonts: 
    - family: CarmenSans
      fonts: 
        - asset: assets/font/CarmenSans-Bold.ttf
        - asset: assets/font/CarmenSans-Medium.ttf
        - asset: assets/font/CarmenSans-Regular.ttf
        - asset: assets/font/CarmenSans-SemiBold.ttf
        - asset: assets/font/CarmenSans-Thin.ttf
        - asset: assets/font/CarmenSans-Light.ttf
  uses-material-design: true

